### ISSUE TITLE
CODEX CRC data segmentation files

### ISSUE THREAD

**Issue by huayingq1996** [KerenLab/CellSighter#3]
Hi,

I wanted to experiment CellSighter with the CODEX CRC data you guys used for benchmarking, but I couldn't find the segmentation files in the data sources listed in the original CRC paper. Could you please point me to where the segmentation file is?

**Comment by yaelAmitay** [comment]
Sorry for the delay, the original CODEX CRC's segmentations are from Schurch lab. You can ask them for their segmentation.
