### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by smith6jt-cop** [KerenLab/CellSighter#6]
Hello,

Installation error on Windows 10, trying to install dependencies from requirements.txt and getting:

`(Cellsighter) C:\Users\smith6jt>pip install -r .\CellSighter\requirements.txt
Collecting matplotlib==3.3.3 (from -r .\CellSighter\requirements.txt (line 1))
  Downloading matplotlib-3.3.3.tar.gz (37.9 MB)
     ---------------------------------------- 37.9/37.9 MB 29.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy==1.19.2 (from -r .\CellSighter\requirements.txt (line 2))
  Downloading numpy-1.19.2.zip (7.3 MB)
     ---------------------------------------- 7.3/7.3 MB 58.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [63 lines of output]
      Running from numpy source directory.
      setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      warning: _generator.pyx:3226:8: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              for i in range(1, RK_STATE_LEN):
                  self.rng_state.key[i] = val[i]
              self.rng_state.pos = i

              self._bitgen.state = &self.rng_state
              self._bitgen.next_uint64 = &mt19937_uint64
                                         ^
      ------------------------------------------------------------

      _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\bit_generator.pyx
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Traceback (most recent call last):
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-install-o4rosbln\numpy_6c70b0fa4dd3454a87c3e27936b4cab0\tools\cythonize.py", line 235, in <module>
          main()
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-install-o4rosbln\numpy_6c70b0fa4dd3454a87c3e27936b4cab0\tools\cythonize.py", line 231, in main
          find_process_files(root_dir)
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-install-o4rosbln\numpy_6c70b0fa4dd3454a87c3e27936b4cab0\tools\cythonize.py", line 222, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-install-o4rosbln\numpy_6c70b0fa4dd3454a87c3e27936b4cab0\tools\cythonize.py", line 188, in process
          processor_function(fromfile, tofile)
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-install-o4rosbln\numpy_6c70b0fa4dd3454a87c3e27936b4cab0\tools\cythonize.py", line 77, in process_pyx
          subprocess.check_call(
        File "C:\Users\smith6jt\AppData\Local\anaconda3\envs\Cellsighter\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\smith6jt\\AppData\\Local\\anaconda3\\envs\\Cellsighter\\python.exe', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
      Cythonizing sources
      Traceback (most recent call last):
        File "C:\Users\smith6jt\AppData\Local\anaconda3\envs\Cellsighter\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\smith6jt\AppData\Local\anaconda3\envs\Cellsighter\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\smith6jt\AppData\Local\anaconda3\envs\Cellsighter\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-build-env-rvd8y6a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-build-env-rvd8y6a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 249, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\smith6jt\AppData\Local\Temp\pip-build-env-rvd8y6a2\overlay\Lib\site-packages\setuptools\build_meta.py", line 142, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 499, in <module>
          setup_package()
        File "setup.py", line 479, in setup_package
          generate_cython()
        File "setup.py", line 274, in generate_cython
          raise RuntimeError("Running cythonize failed!")
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by smith6jt-cop** [comment]
What version of Python should be used?

**Comment by smith6jt-cop** [comment]
Installed Python 3.8 and getting:

`(Cellsighter) C:\Users\smith6jt>pip install -r .\CellSighter\requirements.txt
Collecting matplotlib==3.3.3 (from -r .\CellSighter\requirements.txt (line 1))
  Using cached matplotlib-3.3.3-cp38-cp38-win_amd64.whl (8.5 MB)
Collecting numpy==1.19.2 (from -r .\CellSighter\requirements.txt (line 2))
  Using cached numpy-1.19.2-cp38-cp38-win_amd64.whl (13.0 MB)
Collecting opencv_python==4.4.0.46 (from -r .\CellSighter\requirements.txt (line 3))
  Using cached opencv_python-4.4.0.46-cp38-cp38-win_amd64.whl (33.5 MB)
Collecting pandas==1.1.4 (from -r .\CellSighter\requirements.txt (line 4))
  Using cached pandas-1.1.4-cp38-cp38-win_amd64.whl (8.9 MB)
Collecting Pillow==9.3.0 (from -r .\CellSighter\requirements.txt (line 5))
  Using cached Pillow-9.3.0-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting scikit_learn==1.1.3 (from -r .\CellSighter\requirements.txt (line 6))
  Using cached scikit_learn-1.1.3-cp38-cp38-win_amd64.whl (7.5 MB)
Collecting scipy==1.5.2 (from -r .\CellSighter\requirements.txt (line 7))
  Using cached scipy-1.5.2-cp38-cp38-win_amd64.whl (31.4 MB)
Collecting seaborn==0.12.1 (from -r .\CellSighter\requirements.txt (line 8))
  Using cached seaborn-0.12.1-py3-none-any.whl (288 kB)
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement torch==1.8.0a0+1606899 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1)
ERROR: No matching distribution found for torch==1.8.0a0+1606899`

**Comment by yaelAmitay** [comment]
Hi,
The version should be 3.8.5. 
There was a problem with the requirements file. I fixed it. Let me know if it still doesn't work.
Thanks
